### ISSUE TITLE
How to handle "little" variations of a language with less code.

### ISSUE THREAD

**Issue by DFFZMXJ** [popphp/pop-i18n#1]
There are many variations in most languages like singular and plural in English, prepositions (in, on, at...), etc. 

It doesn't seem worth enumerating variations separately like that below:

```xml
<!--Unrelated code is ignored.-->
<locale region="US" name="English (US)" native="English (US)">
    <text>
        <source>关注他</source>
        <output>Follow him</output>
    </text>
    <text>
        <source>关注她</source>
        <output>Follow her</output>
    </text>
    <text>
        <source>关注Ta</source>
        <output>Follow them</output>
    </text>
</locale>
```

And sometimes translations and original text can't be so corresponding. e.g. In Chinese, whether in (a fragment of time), on (a specific day) or at (a moment, or night/noon), we use "在" or "于" (no distinctions) as the preposition. How can I translate it into English?

**Comment by nicksagona** [comment]
I think I understand what you're asking. Unfortunately, at this time, the functionality is really 1-to-1 in regards to "source" language to "output" language. So it can't really handle a sort of "dynamic" mapping of multiple possible inputs to a single output, or vice-versa. It does support locale definitions to allow the output to alter based on the locales ("en_US" vs "en_GB", for example.) And of course, it allows for parameters to swap out constant values within the language string (like a name like "John" for example.)

All of that said, I'm not sure those features would help solve the issue you've brought up. I don't know if one possible idea would be supporting "catch-all" arrays in the source and/or output nodes to route a group of possible language strings into one output result? Or vice versa? Does something like that make sense or might be in the right direction? Let me know your thoughts on that.

**Comment by DFFZMXJ** [comment]
Maybe it will work.

e.g. There's a string: `There be %1 user/users in this forum.`

I wonder a easy way to keep it grammatically correct.

Personally, the way below is easy.

```xml
<!--A function to tell whether it's singular, plural, etc.-->
<number region="US" name="English (US)" native="English (US)">
    return x==1?'singular':'plural';
</number>
<locale region="US" name="English (US)" native="English (US)">
    <text>
        <source>此论坛有%1用户。</source>
        <output number="singular">There's one user in this forum.</output>
        <output number="plural">There're %1 users in this forum.</output>
    </text>
    <!--a translation that doesn't differentiate number of noun-->
    <text>
        <source>你已被ban.</source>
        <output>You've been banned.</output>
    </text>
</locale>
```

Add another argument as the number when invoking:

```php
$lang->__(
  '此论坛有%1用户。',
  [233],
  233); //This argument. For a string that doesn't differentiate singular or plural, ignore it.
```

**Comment by nicksagona** [comment]
Just an update, I've started working on a concept to handle this feature we've been talking about. It's been pushed up to v3-dev. I still need to test a few things, then we can test it out.

**Comment by nicksagona** [comment]
Ok I just released 3.1.0 that has support to handle multiple variations of possible translation outputs.

The XML should look like this:
```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE language [
        <!ELEMENT language ANY>
        <!ELEMENT locale ANY>
        <!ELEMENT text (source,output)>
        <!ELEMENT source ANY>
        <!ELEMENT output ANY>
        <!ATTLIST language
                src       CDATA    #REQUIRED
                output    CDATA    #REQUIRED
                name      CDATA    #REQUIRED
                native    CDATA    #REQUIRED
                >
        <!ATTLIST locale
                region    CDATA    #REQUIRED
                name      CDATA    #REQUIRED
                native    CDATA    #REQUIRED
                >
        ]>
<language src="en" output="fr" name="French" native="Français">
    <locale region="FR" name="France" native="France">
        <text>
            <source>Hello, my name is %1. I love to program %2.</source>
            <output>
                <output alt="primary">Bonjour, mon nom est %1. Je aime programmer %2.</output>
                <output alt="secondary">Bonjour, je aime programmer %2. Mon nom est %1</output>
            </output>
        </text>
        <text>
            <source>I have been programming %1 for %2 years.</source>
            <output>
                <output>Je programme %1 depuis %2 ans.</output>
                <output>Depuis %2 ans, je programme %1</output>
            </output>
        </text>
    </locale>
</language>
```
and the JSON:

```json
{
  "language"  : {
    "src"    : "en",
    "output" : "fr",
    "name"   : "French",
    "native" : "Français",
    "locale" : [{
      "region" : "FR",
      "name"   : "France",
      "native" : "France",
      "text"   : [
        {
          "source" : "Hello, my name is %1. I love to program %2.",
          "output" : {
            "primary" : "Bonjour, mon nom est %1. Je aime programmer %2.",
            "secondary" : "Bonjour, je aime programmer %2. Mon nom est %1"
          }
        },
        {
          "source" : "I have been programming %1 for %2 years.",
          "output" : [
            "Je programme %1 depuis %2 ans.",
            "Depuis %2 ans, je programme %1"
          ]
        }
      ]
    }]
  }
}
```

**Comment by nicksagona** [comment]
The `__()` and `_e()` methods now take a 3rd parameter to designate the specific output you want. You can have it called by a key, i.e. "primary" or "secondary" or just by a number:

```php 
// Using array key 'secondary'
$lang->_e('Hello, my name is %1. I love to program %2.', ['Nick', 'PHP], 'secondary');
```
```php
// Using array key 1
$lang->_e('I have been programming %1 for %2 years', ['PHP, '20'], 1);
```
Let me know if this helps solve the issue for you. Thanks.

**Comment by DFFZMXJ** [comment]
Great! Thank you so much!
